using Newtonsoft.Json;
using System.Collections.Generic;

namespace MuTest.CoverageAnalyzer.Model.Json
{
    public class Class
    {
        private static readonly ClassIsAutoGeneratedResolver IsAutoGeneratedResolver = new ClassIsAutoGeneratedResolver();
        private readonly string _codeRootPath;

        public Class(string codeRootPath)
        {
            _codeRootPath = codeRootPath;
        }

        [JsonProperty("ClassName")]
        public string ClassName { get; set; }

        [JsonProperty("ClassPaths")]
        public List<string> ClassPaths{ get; set; }

        [JsonProperty("IsAutoGenerated")]
        public bool IsAutoGenerated => IsAutoGeneratedResolver.IsClassAutoGenerated(ClassPaths, _codeRootPath);

        [JsonProperty("HUT")]
        public Hut Hut { get; set; }
    }
}