using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace MuTest.CoverageAnalyzer
{
    internal class ClassIsAutoGeneratedResolver
    {
        public bool IsClassAutoGenerated(IEnumerable<string> relativeClassPaths, string codeRootPath)
        {
            // Consider a class as auto generated only if all its declarations are auto generated.
            return relativeClassPaths.All(classPath =>
            {
                var absoluteClasPath = Path.Combine(codeRootPath, classPath);
                var classText = File.ReadAllText(absoluteClasPath);
                var isAutoGenerated = classText.Contains("<auto-generated>");
                return isAutoGenerated;
            });

        }
    }

}
